version: '3'

services:
  mongo:
    image: mongo:4.4.5
    container_name: mongo-dev
    restart: always
    networks:
      - map-backend-dev-network
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"

networks:
  map-backend-dev-network:
    driver: bridge
