version: "3"

services:
  api-server:
    build:
      context: .
    container_name: api-server
    image: api-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=mongodb://host.docker.internal:27017/books
    volumes:
      - ./logs:/logs
    networks:
      - app-network
    ports:
      - "3000:3000"
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: es01
    environment:
        - node.name=es01
        - cluster.name=es-docker-cluster
        - cluster.initial_master_nodes=es01
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
        nproc: 65536
        nofile:
            soft: 65536
            hard: 65536
        memlock:
            soft: -1
            hard: -1
    volumes:
        -  data01:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
    networks:
        - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data01:
    driver: local